# docker-compose.yml
services:
  # The 'db' service is for local development/testing only.
  # On Railway use their Managed MySQL service instead
  db:
    image: mysql:8.4
    container_name: microlending-mysql
    restart: unless-stopped
    env_file: .env
    # The container's internal port is 3306.
    volumes:
      - ./db/docker/my.cnf:/etc/mysql/conf.d/my.cnf:ro
# - ./db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: