USE microlending;
SHOW TABLES;
DESCRIBE user;
DESCRIBE wallet_account;
DESCRIBE loan;
SHOW INDEX FROM user;
SHOW INDEX FROM loan_application;
SHOW INDEX FROM loan;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'microlending'
  AND TABLE_NAME IN ('user', 'wallet_account', 'loan', 'loan_application')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;
SELECT kcu.TABLE_NAME, kcu.COLUMN_NAME, kcu.REFERENCED_TABLE_NAME, kcu.REFERENCED_COLUMN_NAME, rc.DELETE_RULE
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
  ON kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE kcu.TABLE_SCHEMA = 'microlending'
  AND kcu.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY kcu.TABLE_NAME
LIMIT 10;
