USE microlending;
START TRANSACTION;
SELECT 'BEFORE INSERT - Checking if rollback_test exists:' as status;
SELECT COUNT(*) as count FROM user WHERE email = 'rollback_test@test.com';
INSERT INTO user (email, password_hash, full_name, role) VALUES ('rollback_test@test.com', SHA2('test', 256), 'Rollback Test User', 'borrower');
SELECT 'AFTER INSERT - User exists in transaction:' as status;
SELECT COUNT(*) as count FROM user WHERE email = 'rollback_test@test.com';
ROLLBACK;
SELECT 'AFTER ROLLBACK - User should NOT exist:' as status;
SELECT COUNT(*) as count FROM user WHERE email = 'rollback_test@test.com';
START TRANSACTION;
SELECT 'BEFORE INSERT - Checking if commit_test exists:' as status;
SELECT COUNT(*) as count FROM user WHERE email = 'commit_test@test.com';
INSERT INTO user (email, password_hash, full_name, role) VALUES ('commit_test@test.com', SHA2('test', 256), 'Commit Test User', 'borrower');
SELECT 'AFTER INSERT - User exists in transaction:' as status;
SELECT COUNT(*) as count FROM user WHERE email = 'commit_test@test.com';
COMMIT;
SELECT 'AFTER COMMIT - User persisted permanently:' as status;
SELECT id, email, full_name FROM user WHERE email = 'commit_test@test.com';
DELETE FROM user WHERE email = 'commit_test@test.com';
